---
- name: apache-start
  service:
    name=apache2
    start=started
  become: yes
  become_method: sudo

- name: apache-stop
  service:
    name=apache2
    start=stopped
  become: yes
  become_method: sudo

- name: apache-reload
  service:
    name=apache2
    state=reloaded
  become: yes
  become_method: sudo

- name: apache-restart
  service:
    name=apache2
    state=restarted
  become: yes
  become_method: sudo
